# Generated by Django 5.2.5 on 2025-08-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkApp', '0002_alter_organization_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingslot',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='parkingslot',
            name='distance',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='parkingslot',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='parkingslot',
            name='name',
            field=models.CharField(default='Default name', max_length=255),
            preserve_default=False,
        ),
    ]
