# Generated by Django 5.2.5 on 2025-08-30 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkApp', '0003_parkingslot_address_parkingslot_distance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('vehicle_type', models.CharField(choices=[('2W', 'Two Wheeler'), ('4W', 'Four Wheeler')], max_length=2)),
                ('vehicle_number', models.CharField(max_length=20)),
                ('vehicle_brand', models.CharField(blank=True, max_length=100)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('token', models.CharField(max_length=20, unique=True)),
                ('pin', models.CharField(max_length=10)),
                ('status', models.CharField(default='confirmed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='parkApp.parkingslot')),
            ],
        ),
    ]
